version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: kc_postgres
    restart: always
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak"]
      interval: 5s
      timeout: 5s
      retries: 10

  keycloak:
    build: .
    container_name: keycloak
    restart: always
    environment:
        KC_DB: postgres
        KC_DB_URL: "jdbc:postgresql://postgres:5432/keycloak"
        KC_DB_USERNAME: keycloak
        KC_DB_PASSWORD: your_db_password
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: supersecret
        KC_HOSTNAME: ciel69-keycloak-kanji-b601.twc1.net
        KC_PROXY: edge
        KC_HTTP_ENABLED: true
        KC_HTTP_PORT: 8080
        KC_HOSTNAME_STRICT: false
    command: start
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

